CREATE DATABASE IF NOT EXISTS boeken;

USE boeken;

CREATE TABLE IF NOT EXISTS boek
(
    location  VARCHAR(20),
    naam      VARCHAR(60),
    bookrank  integer,
    datum     DATE,
    schrijver VARCHAR(20),
    uitgever  VARCHAR(20),
    kosten    DECIMAL,
    info      LONGTEXT,
    image     VARCHAR(300)
);

INSERT INTO boek(location, naam, bookrank, datum, schrijver, uitgever, kosten, info, image)
VALUES ('/book1.php','Jo Nesbo Koningsrijk', '1', '2001-01-06', 'Jo Nesbo', 'Cargo', '22.99', 'Een ijzingwekkende tragedie over twee broers, één vrouw en een nooit opgeloste moord uit het verleden.', 'https://images.mind-books.nl/libris/book/cover/9789403108711?hash=f2d2607&width=160'),
       ('/book2.php','Valse getuige', '2','2002-06-04', 'Karin Slaughter', 'HarperCollins', '22.99', 'Leigh en haar zus Callie zijn geen slechte mensen, maar op een avond meer dan twintig jaar geleden hebben ze iets vreselijks gedaan. Het resulteerde in een leven dat getekend werd door schuldgevoelens, verraad en geheimen. Jaren later heeft Leigh, inmiddels werkzaam bij een succesvol advocatenkantoor, de herinneringen aan die avond verdrongen. Tot ze tegen haar wil gedwongen wordt om een nieuwe cliënt aan te nemen en de grond onder haar voeten wegvalt. Want de man weet wat er destijds is gebeurd. Hij weet wat Leigh en Callie hebben gedaan. En tenzij ze hem stoppen, zal hij hun levens verwoesten…', 'https://images.mind-books.nl/libris/book/cover/9789402707991?hash=80f978e&width=160'),
       ('/book3.php','Dodelijk Spel', '3','2001-02-10', 'David Baldacci', 'A.W. Bruna Uitgevers', '22.99', 'Onderweg naar Californië maakt Aloysius Archer een tussenstop in Reno. Nog geen 24 uur later is hij de trotse eigenaar van een peperdure, zeer zeldzame Franse sportauto, heeft hij een reisgenoot gevonden in de mysterieuze danseres Liberty Callahan en moet hij zich enkele zwaar bewapende criminelen van het lijf houden. Geluk bij een ongeluk: Liberty blijkt niet alleen zeer verleidelijk te zijn, maar ook uitstekend met een pistool overweg te kunnen. Het zijn twee eigenschappen die hun niet veel later uitstekend van pas komen, wanneer privé-detective Archer in een politiek wespennest belandt waarin een schatrijke familie, een nachtclub en een mysterieuze militaire installatie de hoofdrollen spelen.', 'https://images.mind-books.nl/libris/book/cover/9789400513716?hash=21d5e38&width=160'),
       ('/book4.php','Niemand zeggen', '4','1996-05-09', 'Helen Grace 10', 'Boekerij', '20.99', 'Na covid-19 bevindt het land zich in een van de zwaarste -recessies ooit. Nog nooit heeft inspecteur Helen Grace met zo veel geweld en onrust te maken gehad. Voor het eerst in haar leven is ze bang om de controle te verliezen: haar trouwe partner Charlie is met zwangerschapsverlof en tegelijkertijd doet haar collega Joseph Hudson er álles aan om haar het leven zuur te maken. Drie moordzaken houden Helen ’s nachts wakker: een oude, rijke man, vermoord tijdens een inbraak in zijn immense huis; een jonge zorg-manager, in zijn auto doodgestoken met een schroevendraaier; en een jonge studente, aangerand en doodgeknuppeld in het plaatselijke park. Dan krijgt ze bericht dat de privédetective die onderzoek deed naar deze zaken levend in brand is gestoken. Net als Helen dacht hij dat zo veel geweld in korte tijd geen toeval kon zijn, maar zelfs met deze aanwijzing kan ze het verband niet zien. En de tijd begint te dringen, want de dader gaat geen enkele uitdaging uit de weg om zichzelf te bewijzen.', 'https://images.mind-books.nl/libris/book/cover/9789022591208?hash=4594fed&width=160'),
       ('/book5.php','Wie niet horen wil', '5','2008-12-28', 'Nicci French', 'Ambo|Anthos', '22.99', 'Wie niet horen wil van Nicci French gaat over Tess, die net haar leven weer op orde heeft. Jason en zij zijn een jaar geleden vriendschappelijk uit elkaar gegaan en delen de voogdij over hun dochtertje Poppy. Ze moet nog wennen aan haar nieuwe situatie, maar is blij met de hulp die ze krijgt van haar vrienden. Dat Jason inmiddels is getrouwd, daar probeert ze te zich overheen te zetten. Zelf is ze ook weer aan het daten en ze is best gelukkig, houdt ze zich voor. Totdat haar dochtertje Poppy vreemde taal begint uit te slaan en een tekening maakt met zwart wascokrijt. Een tekening waarop een figuur te zien is die van een toren valt. Tess raakt ervan overtuigd dat Poppy getuige is geweest van een misdrijf. Ze stapt naar de politie, maar daar wordt ze niet geloofd. Dan besluit ze zelf op onderzoek te gaan… Nicci French heeft met Wie niet horen wil wederom een spannende psychologische thriller geschreven, met een uiterst onverwachte ontknoping.', 'https://images.mind-books.nl/libris/book/cover/9789026352126?hash=&width=160'),
       ('/book6.php','Orakel', '6','2021-01-01', 'Thomas Olde Heuvelt', 'Boekerij', '20.99', 'Op een mistige winterochtend zien Luca Wolf en Emma Reich een achttiende-eeuws zeilschip in een bollenveld bij de duinen liggen. Orakel, staat er op de achtersteven. Het ligt er, in alle opzichten, verkeerd. Emma kan haar nieuwsgierigheid niet bedwingen en gaat het luik op het hellende dek binnen. Niemand ziet haar nog terug. Luca blijft verbijsterd achter: hij wilde haar wel achternagaan, maar iets hield hem tegen. De uitdrukking op haar gezicht toen ze door het luik ging, maakte hem bang… Niet veel later zijn er elf mensen verdwenen, worden Luca en zijn moeder afgeschermd van de wereld vastgehouden en staan de geheime diensten voor een raadsel. Alles moet uit de kast worden gehaald om een mediastorm te voorkomen. Maar als men graaft in een ver verleden om het mysterie van de Orakel te ontrafelen, blijkt het schip een voorbode te zijn van iets onheilspellends.', 'https://images.mind-books.nl/libris/book/cover/9789022591109?hash=c398b7a&width=160'),
       ('/book7.php','Later', '7','2021-04-23', 'Stephen King', 'Boekerij', '20.99', 'Normaal ziet hij de doden maar voor een paar dagen. Maar wat als ze ervoor kiezen om langer te blijven? Jamie Conklin is enig kind. Als zoon van een alleenstaande moeder die lastig rond kan komen, wil hij niets liever dan een normale jeugd. Maar jammer genoeg voor Jamie is hij allesbehalve normaal… Geboren met een bovennatuurlijke gave die hij van zijn moeder geheim moet houden, ziet Jamie dingen die niemand anders kan zien en weet hij meer dan eigenlijk mogelijk zou moeten zijn. Wanneer een rechercheur van de New Yorkse politie hem betrekt bij de klopjacht op een moordenaar, komt Jamie opnieuw oog in oog te staan met een overledene. Maar de prijs die deze keer staat op het gebruiken van zijn gaven is veel hoger dan hij ooit had gedacht – deze geest is namelijk niet van plan weg te gaan. Later is een krachtig en spookachtig verhaal met ondertonen van de klassieke thriller It. Een onvergetelijke zoektocht naar wat ervoor nodig is om op te staan tegen het kwaad en al zijn gezichten.', 'https://images.mind-books.nl/libris/book/cover/9789022592809?hash=c55c2ca&width=160'),
       ('/book8.php','Mimic', '8','2021-04-08', 'Daniel Cole', 'Dwarsligger', '18.99', 'Dwarsligger 718 is Mimic van Daniel Cole, een knaller van een serial killer thriller. Van de schrijver van de Ragdoll-trilogie. Hij moordt voor zijn kunst. Zij wordt zijn meesterwerk. 1989. Rechercheur Benjamin Chambers is op het spoor van een seriemoordenaar die met de lichamen van zijn slachtoffers beroemde kunstwerken imiteert. Als Chambers dit onderzoek bijna met zijn leven moet bekopen, loopt de zaak vervolgens dood door gebrek aan bewijs. De moordenaar verdwijnt, zijn verzameling onafgemaakt. 1996. Rechercheur Jordan Marshall heeft zich in rap tempo omhooggewerkt binnen de Londense politie. Ze heeft nieuw bewijs verzameld in de oude zaak en voegt zich bij Chambers en zijn partner om het dossier te heropenen. Maar het onderzoek brengt een nieuwe golf van gruweldaden met zich mee… Mimic is van begin tot eind een verslavende leeservaring, met geweldige personages en een bloedstollend spannende plot.Over de Ragdoll-serie: 5 sterren ‘Cole typeert zijn personages meesterlijk en blinkt uit in het bedenken van intrigerende, gecompliceerde moorden. Een thriller van het hoogste niveau.’ – VN Detective & Thrillergids ‘Voor lezers met stalen zenuwen.’ – Noordhollands Dagblad ‘Spanning, prettig zwartkomisch, onvoorspelbaar.’ – De Telegraaf', 'https://images.mind-books.nl/libris/book/cover/9789024594894?hash=bdab81d&width=160'),
       ('/book9.php','De camino', '9','2018-04-12', 'Anya Niewierra', 'Luitingh-Sijthoff', '20.99', 'Het nieuwe boek van Hebban Thrillerprijs-winnaar Anya Niewierra. Een jaar na de zelfmoord van haar man besluit Lotte zijn route over de Camino te herlopen. Maar dan ontrafelt ze een duister geheim. De 44-jarige chocolatier Lotte Bonnet woont al jaren gelukkig in Zuid-Limburg met haar man Emil, een voormalige vluchteling uit Bosnië. Maar dan pleegt Emil onverwacht zelfmoord tijdens het lopen van de Camino en blijft Lotte ontredderd achter. Als ze elf maanden later naar Bosnië reist om zijn as uit te strooien, ontdekt Lotte dat Emil heeft gelogen over zijn identiteit. Ze schakelt een advocaat uit Sarajevo in om onderzoek te doen naar zijn verleden, en die komt tot een schokkende ontdekking. Ondertussen gaat Lotte zelf de Camino lopen, exact volgens de route en planning van Emil. Ze wil achterhalen wat hem tot zijn wanhoopsdaad dreef. Maar iemand volgt haar, iemand die niet wil dat ze de waarheid ontdekt.', 'https://images.mind-books.nl/libris/book/cover/9789024582273?hash=dc73aec&width=160'),
       ('/book10.php','Kopje-onder', '10','2017-03-06', 'Jeff Kinney', 'de Fontein Jeugd', '15.99', 'De familie Botermans strandt op een camperpark. Daar slaat de vakantiestemming om: een epische wolkbreuk en stijgend water… Gaat Bram kopje-onder? Kopje-onder is deel 15 in de megasuccesvolle en supergrappige serie Het leven van een Loser van Jeff Kinney. Voor jongens en meiden van 8 jaar en ouder. Supergrappig vertaald door Hanneke Majoor. Op zoek naar avontuur reist de familie Botermans met de camper door het land. Maar wanneer ze stranden op een camperpark, niet echt een zomerparadijs, slaat de vakantiestemming om: een epische wolkbreuk en stijgend water… dat wordt pompen of verzuipen! Is de vakantie nog te redden, of wordt dit een nieuw dieptepunt? Gaat Bram kopje-onder?', 'https://images.mind-books.nl/libris/book/cover/9789026148026?hash=6ba2341&width=160'),
       ('/book11.php','Het bloemenmeisje', '11','2000-07-03', 'Anya Niewierra', 'Luitingh-Sijthoff', '15.00', '1988. Hoog in de Franse Pyreneeën vindt de politie een verwilderde tiener bij het lijk van haar moeder. Het meisje krijgt de naam Nina Fleurie, het bloemenmeisje. De moord op haar moeder wordt nooit opgelost. Dertig jaar later ontwikkelt Nina geneesmiddelen op basis van kruiden. Zakelijk heeft ze succes, maar privé is ze een zonderling. Dan komt Nina erachter dat ze een tweelingzus heeft. Samen duiken ze in het bizarre verleden van hun moeder. Als haar zus verdwijnt, raakt de zoektocht in een stroomversnelling. Na een bezoek aan een grot in Zuid-Limburg en een klooster in de Ardennen stuit Nina op de mensen die het leven van haar moeder verwoestten, waarna een onbekende nu de jacht op haar opent...', 'https://media.s-bol.com/O7E6wjwzNA5B/789x1200.jpg'),
       ('/book12.php','Het dossier', '12','2015-11-12', ' Anya Niewierra', 'B for books BV', '15.99', 'Na haar debuut Vrij uitzicht, dat vele nominaties in de wacht sleepte, komt Anya Niewierra nu met Het Dossier. De ingrediënten - de voormalige DDR, kunstvervalsing van belangrijke expressionisten én een orgaanroof - zijn door Niewierra subtiel in elkaar vervlochten tot dé ultieme thriller: hoever ga je om te overleven? De 46-jarige Josta Bresse wordt slachtoffer van een orgaanroof. De Nederlandse recherche stuit tijdens het onderzoek op het duistere DDR-verleden van Josta. Daarom keert Josta terug naar Oost-Berlijn, waar ze destijds als kunstvervalser deel uitmaakte van de zogenaamde Königstein Gruppe. Dit team van vervalsers dat werkte in opdracht van het toenmalige DDR-regime, werd vlak voor de val van de Muur door de Stasi afgevoerd naar de gevangenis Hohenschönhausen. Reden: een geheim Dossier. 25 jaar later blijkt dit Dossier nog steeds reden voor moord. Opgejaagd als een wild dier probeert Josta Bresse het Dossier in handen te krijgen, maar de macht van de daders blijkt groot. Enorm groot. Anya Niewierra (1964) is algemeen-directeur van de vvv Zuid-Limburg en bestuurslid van de Europese organisatie Necstour. In 2013 debuteerde zij met de thriller Vrij uitzicht, die genomineerd werd voor de Debutantenprijs, de Schaduwprijs en voor de Beste Thriller.', 'https://media.s-bol.com/oEyNwkK5qW3/800x1200.jpg'),
       ('/book13.php','Daar waar de rivierkreeften zingen', '13','2000-05-07', 'Delia Owens', 'The House of Books', '10.99', 'Een jong meisje wordt verlaten, steeds weer. Diep in het moeras, in schrijnende eenzaamheid, is de natuur, die het leven in alle vormen laat zien, alles voor Kya. Maar wat als de natuur het enige is waar je van kunt leren? Wat doet dat met hoe je naar het leven kijkt? Kya leert overleven, ze leert lezen en leven. Een teruggetrokken jonge vrouw, een met de meeuwen, vaart over het moeras en omzeilt menselijk contact. Als ze in contact komt met twee jongemannen verschuift er iets in Kya en in haar leven.', 'https://media.s-bol.com/RPn5BL00DBwY/772x1200.jpg'),
       ('/book14.php','De wintertuin', '14','2001-03-06', 'Kristin Hannah', 'Boekerij', '20.99', 'Anya heeft nooit willen vertellen wat er tijdens de oorlog is gebeurd. Maar haar geheim is het enige wat haar dochters weer bij elkaar kan brengen Een hartverscheurende oorlogsroman van de auteur van De nachtegaal ‘Een ontroerende roman over vriendschap en familie, verlies en troost.’ Algemeen Dagblad De zussen Meredith en Nina zijn erg verschillend van aard. De een bleef thuis om haar kinderen op te voeden en het familiebedrijf te runnen, de ander volgde haar droom om fotojournalist te worden en reisde de hele wereld over. Wanneer hun vader ziek wordt beseffen ze dat ze hun krachten moeten bundelen. Hun afkeurende moeder Anya is zelfs nu niet in staat troost te bieden. Op zijn sterfbed vraagt hun vader Meredith en Nina nog één keer te luisteren naar het Russische sprookje dat hun moeder altijd vertelde, maar waarvan ze nooit het einde hebben gehoord. Zo komt eindelijk Anya’s tragische verleden in het door oorlog verscheurde Leningrad aan het licht. En haar dochters luisteren, helemaal tot het einde…', 'https://media.s-bol.com/ZY2VN0kXzGqQ/769x1200.jpg'),
       ('/book15.php','De vergeten kamer', '15','2021-03-06', 'Ann Mah', 'Boekerij', '10.99', 'Kate, een jonge Amerikaanse vrouw, studeert voor haar sommeliersdiploma. Ze gaat op bezoek bij de wijngaard van haar familie in Frankrijk om haar kennis van de lokale bourgogne nog wat aan te scherpen. Wanneer ze haar neef helpt bij het opruimen van de enorme wijnkelder, ontdekt ze een geheime schuilplaats uit de Tweede Wereldoorlog, en vindt ze een stapel oude verzetspamfletten en een grote voorraad waardevolle wijnen. Geïntrigeerd begint ze te graven in haar familiegeschiedenis. Dan ontrafelt zich een verhaal dat al zestig jaar in de doofpot is gestopt: over een tienermeisje dat de bezetting probeerde te overleven zonder haar morele overtuigingen overboord te zetten. Heeft haar vooraanstaande familie, groot geworden in de wijnhandel, zich in de oorlog misschien niet zo goed gedragen als zij altijd dacht?', 'https://media.s-bol.com/ywknZ094XyZg/782x1200.jpg');

SELECT * FROM boek;